apiVersion: v1
kind: Service
metadata:
  name: monitor-mcp-server
  labels:
    app.kubernetes.io/name: monitor-mcp-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: monitor-mcp-server
